# -*- coding: utf-8 -*-
"""get_palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uccyVx3XnAijU8wCOcwtFotJP9UvL-lJ
"""

def is_palindrome(word):
    return word == word[::-1]

def find_palindromes_bruteforce(input_word):
    palindromes = []
    n = len(input_word)
    for i in range(n):
        for j in range(i + 1, n):
            if is_palindrome(input_word[i:j+1]):
                palindromes.append(input_word[i:j+1])
    return palindromes

string = 'banana'
palindromes = find_palindromes_bruteforce(string)
print('Palindrome substrings of ',string,' are:\n',palindromes)

