# -*- coding: utf-8 -*-
"""hexzagon_area.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rz0IfZKWz0JWV2pG9t-fe2XwkVsMyzca
"""

def area(a):
  return (3*3**0.5*a**2)/2


a=10
print("area of hexagon is:", area(a))