# -*- coding: utf-8 -*-
"""largest_ele.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQF-O0TqAn06ckXx0gXvOmwjyVr2Fr-Q
"""

def largest(l):
  max=l[0]
  for i in range(len(l)-1):

    if (l[i]<l[i+1]):
      max=l[i+1]
  return max

l=[1,4,7,3,9]
print(largest(l))