# -*- coding: utf-8 -*-
"""valid_email.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_30yzvkF-GwS0sGUIctO7j3vo_rhNeW
"""



def is_valid(email):
  if len(email)>256:
    return False
  else:
    if email[0].isalpha() and email[0].isnumeric():
      if '@' in email and email.count('@')==1:
        a,b= email.split('@')
        if a and b:
          if '.' in b:
            c,d = email.split('.')
            if c and d:
              e= d[d.rfind('.')+1:]
              if e:
                return True
              else:
                return False
            else:
              return False
          else:
            return False
        else:
          return False
      else:
        return False
    else:
      return False



email= input("enter a email ")

print(is_valid(email))